# Generated by Django 6.0.4 on 2026-05-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_student_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
